package hypelabs.com.hypepubsub;

import java.security.NoSuchAlgorithmException;

import com.hypelabs.hype.Instance;

/**
 * This class represents an Hype client.
 */
public class Client
{
    /**
     * Hype instance of the client
     */
    final Instance instance;

    /**
     * Key of the client. The key is generated by hashing the Hype ID using the SHA-1 algorithm.
     */
    byte key[];

    /**
     * Client class constructor.
     *
     * @param instance Hype instance of the client object to be created.
     * @throws NoSuchAlgorithmException Throws this exception when the SHA-1 algorithm is not
     *                                  available on the device.
     */
    public Client(Instance instance) throws NoSuchAlgorithmException
    {
        this.instance = instance;
        this.key = GenericUtils.getByteArrayHash(instance.getIdentifier());
    }
}
